enum SURROUNDING_TILE {
  ST_NORTH = 1,
  ST_NORTH_EAST = 2,
  ST_EAST = 4,
  ST_SOUTH_EAST = 8,
  ST_SOUTH = 16,
  ST_SOUTH_WEST = 32,
  ST_WEST = 64,
  ST_NORTH_WEST = 128,
  
  ST_CORNERS = ST_NORTH_WEST | ST_NORTH_EAST | ST_SOUTH_WEST | ST_SOUTH_EAST
};

enum TILE_STATE {
  // Corners
  // __
  //|
  //|
  TS_CORNER_TOPLEFT = ST_SOUTH | ST_SOUTH_EAST | ST_EAST,
  TS_CORNER_TOPRIGHT = ST_SOUTH | ST_SOUTH_WEST | ST_WEST,
  
  TS_CORNER_BOTTOMLEFT = ST_NORTH | ST_NORTH_EAST | ST_EAST,
  TS_CORNER_BOTTOMRIGHT = ST_NORTH | ST_NORTH_WEST | ST_WEST,
  
  // Walls
  //|
  //|
  //|
  TS_WALL_LEFT = ST_NORTH | ST_NORTH_EAST | ST_EAST | ST_SOUTH_EAST | ST_SOUTH,
  TS_WALL_RIGHT = ST_NORTH | ST_NORTH_WEST | ST_WEST | ST_SOUTH_WEST | ST_SOUTH,
  
  TS_WALL_TOP = ST_WEST | ST_SOUTH_WEST | ST_SOUTH | ST_SOUTH_EAST | ST_EAST, 
  TS_WALL_BOTTOM = ST_WEST | ST_NORTH_WEST | ST_NORTH | ST_NORTH_EAST | ST_EAST,
  
  // Path
  //| |
  //| |
  //| |
  TS_PATH_HORIZONTAL = ST_WEST | ST_EAST,
  TS_PATH_VERTICAL = ST_NORTH | ST_SOUTH,
  
  TS_SURROUNDED_BY_SELF = 255,
  TS_SURROUNDED_BY_OTHERS = 0,

  // Dead End
  //--
  //|
  //--
  TS_ONE_WAY_LEFT = ST_EAST,
  TS_ONE_WAY_UP = ST_SOUTH,
  TS_ONE_WAY_RIGHT = ST_WEST,
  TS_ONE_WAY_DOWN = ST_NORTH,

  // Corner Edge
  //----
  //|
  //| x
  TS_CORNER_EDGE_TOPLEFT = ST_SOUTH | ST_EAST,
  TS_CORNER_EDGE_TOPRIGHT = ST_SOUTH | ST_WEST,
  
  TS_CORNER_EDGE_BOTTOMLEFT = ST_NORTH | ST_EAST,
  TS_CORNER_EDGE_BOTTOMRIGHT = ST_NORTH | ST_WEST,
  
  // Corner P Edge
  //|
  //|
  //| x
  TS_CORNERP_EDGE_TOPLEFT = TS_WALL_LEFT & ~ST_SOUTH_EAST,
  TS_CORNERP_EDGE_TOPRIGHT = TS_WALL_RIGHT & ~ST_SOUTH_WEST,
  
  TS_CORNERP_EDGE_BOTTOMLEFT = TS_WALL_LEFT & ~ST_NORTH_EAST,
  TS_CORNERP_EDGE_BOTTOMRIGHT = TS_WALL_RIGHT & ~ST_NORTH_WEST,
  
  // Wall Corner
  // 
  //  x
  //-------
  
  //Corner T
  TS_CORNERT_DOWN = TS_WALL_TOP & ~(ST_SOUTH_WEST | ST_SOUTH_EAST),
  TS_CORNERT_RIGHT = TS_WALL_LEFT & ~(ST_NORTH_EAST | ST_SOUTH_EAST),
  TS_CORNERT_LEFT = TS_WALL_RIGHT & ~(ST_NORTH_WEST | ST_SOUTH_WEST),
  TS_CORNERT_UP = TS_WALL_BOTTOM & ~(ST_NORTH_WEST | ST_NORTH_EAST),

  // Corner Tight
};
